# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: cicd

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [ "master", "Issue-**" ]
    # Sequence of patterns matched against refs/tags
    tags: ["publish-corelib*", "publish-xunit*", "publish-nullability*", "publish-jsonquery*"]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test-one-env:
  
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/publish')
    strategy:
      matrix:
        os: [ubuntu-22.04]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Clean previous build output (Debug)
      run: dotnet clean -c Debug
    - name: Build (Debug)
      run: dotnet build -c Debug
    - name: Test (Debug)
      run: dotnet test --verbosity normal -c Debug
    - name: Clean previous build output (Release)
      run: dotnet clean -c Release
    - name: Build (Release)
      run: dotnet build -c Release
    - name: Test (Release)
      run: dotnet test --verbosity normal -c Release
    - name: Publish Benchmark
      run: dotnet publish -c Release LateApexEarlySpeed.Json.Schema.Benchmark/
    - name: Run Benchmark
      run: dotnet LateApexEarlySpeed.Json.Schema.Benchmark/bin/Release/net6.0/publish/LateApexEarlySpeed.Json.Schema.Benchmark.dll

  build-and-test-multiple-env-for-corelib:
  
    if: github.event_name == 'push' && (contains(github.ref, 'refs/tags/publish-corelib') || contains(github.ref, 'refs/tags/publish-nullability') || contains(github.ref, 'refs/tags/publish-jsonquery'))
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Clean previous build output (Debug)
      run: dotnet clean -c Debug
    - name: Build (Debug)
      run: dotnet build -c Debug
    - name: Test (Debug)
      run: dotnet test --verbosity normal -c Debug
    - name: Clean previous build output (Release)
      run: dotnet clean -c Release
    - name: Build (Release)
      run: dotnet build -c Release
    - name: Test (Release)
      run: dotnet test --verbosity normal -c Release
    - name: Publish Benchmark
      run: dotnet publish -c Release LateApexEarlySpeed.Json.Schema.Benchmark/
    - name: Run Benchmark
      run: dotnet LateApexEarlySpeed.Json.Schema.Benchmark/bin/Release/net6.0/publish/LateApexEarlySpeed.Json.Schema.Benchmark.dll
      
  publish-nuget-pack-corelib:    
    
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/publish-corelib')
    needs: build-and-test-multiple-env-for-corelib
    runs-on: ubuntu-22.04
    environment: 'PublishPackages'
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Clean previous build output
      run: dotnet clean -c Release
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --verbosity normal -c Release
    
    - name: Create Nuget pack
      run: dotnet pack LateApexEarlySpeed.Json.Schema/ -c Release
    - uses: actions/upload-artifact@v4
      with:
        name: Upload Nuget pack artifact
        path: LateApexEarlySpeed.Json.Schema/bin/Release/NugetPackage/
        if-no-files-found: error

    - name: Publish Nuget pack (corelib)
      run: dotnet nuget push LateApexEarlySpeed.Json.Schema/bin/Release/NugetPackage/ --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols

  publish-nuget-pack-xunit:    
    
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/publish-xunit')
    runs-on: ubuntu-22.04
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Clean previous build output
      run: dotnet clean -c Release
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --verbosity normal -c Release
    
    - name: Create Nuget pack
      run: dotnet pack LateApexEarlySpeed.Xunit.Assertion.Json/ -c Release
    - uses: actions/upload-artifact@v4
      with:
        name: Upload Nuget pack artifact
        path: LateApexEarlySpeed.Xunit.Assertion.Json/bin/Release/NugetPackage/
        if-no-files-found: error
        
    - name: Publish Nuget pack
      run: dotnet nuget push LateApexEarlySpeed.Xunit.Assertion.Json/bin/Release/NugetPackage/ --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols

  publish-nuget-pack-nullability:    
    
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/publish-nullability')
    needs: build-and-test-multiple-env-for-corelib
    runs-on: ubuntu-22.04
    environment: 'PublishPackages'
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Clean previous build output
      run: dotnet clean -c Release
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --verbosity normal -c Release
    
    - name: Create Nuget pack
      run: dotnet pack LateApexEarlySpeed.Nullability.Generic/ -c Release
    - uses: actions/upload-artifact@v4
      with:
        name: Upload Nuget pack artifact
        path: LateApexEarlySpeed.Nullability.Generic/bin/Release/NugetPackage/
        if-no-files-found: error

    - name: Publish Nuget pack (nullability lib)
      run: dotnet nuget push LateApexEarlySpeed.Nullability.Generic/bin/Release/NugetPackage/ --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols

  publish-nuget-pack-jsonquery:    
    
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/publish-jsonquery')
    needs: build-and-test-multiple-env-for-corelib
    runs-on: ubuntu-22.04
    environment: 'PublishPackages'
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Clean previous build output
      run: dotnet clean -c Release
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --verbosity normal -c Release
    
    - name: Create Nuget pack
      run: dotnet pack JsonQuery.Net/ -c Release
    - uses: actions/upload-artifact@v4
      with:
        name: Upload Nuget pack artifact
        path: JsonQuery.Net/bin/Release/NugetPackage/
        if-no-files-found: error

    - name: Publish Nuget pack (jsonquery lib)
      run: dotnet nuget push JsonQuery.Net/bin/Release/NugetPackage/ --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols
